name: pack
on:
  push:
    tags:
      - "*"

jobs:
  validation:
    uses: "./.github/workflows/validation.yml"
  pack:
    runs-on: ubuntu-latest
    needs: validation
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: little-core-labs/get-git-tag@v3.0.1
      - run: echo ${{ vars.NPM_REGISTRY }}:_authToken=${{ vars.NPM_TOKEN }} >> .npmrc
      - run: npm version $GIT_TAG_NAME --no-git-tag-version
      - run: npm publish --registry ${{ vars.NPM_REGISTRY }} --access public
