name: quality
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main
      - demo
jobs:
  base:
    uses: "./.github/workflows/base.yml"
  lint:
    runs-on: ubuntu-latest
    needs: base
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: actions/cache@v3
        with:
          key: modules-${{ github.sha }}
          path: ./node_modules
      - run: ./.github/scripts/lint.sh
        shell: bash
  test:
    runs-on: ubuntu-latest
    needs: base
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: actions/cache@v3
        with:
          key: modules-${{ github.sha }}
          path: ./node_modules
      - run: ./.github/scripts/test.sh
        shell: bash
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: actions/cache@v3
        with:
          key: modules-${{ github.sha }}
          path: ./node_modules
      - run: ./.github/scripts/build.sh
        shell: bash
      - uses: actions/cache@v3
        with:
          key: build-${{ github.sha }}
          path: ./dist
